# Generated by Django 5.2.1 on 2025-05-24 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoparts', '0004_actualizar_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialcompra',
            name='perfil',
        ),
        migrations.AlterModelOptions(
            name='carritoitem',
            options={},
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='rut',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='telefono',
        ),
        migrations.DeleteModel(
            name='DetalleCompra',
        ),
        migrations.DeleteModel(
            name='HistorialCompra',
        ),
    ]
